spring:
  datasource:
    url: jdbc:mysql://localhost:3306/software
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1441
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
